title: A Training Blog about Github Pages!
author: Br3W7h1S
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a page created for training purposes related to Github Pages training and education.

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
